[package]
name = "unnamed_cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unnamed_cms_lib = { path = "./lib" }
actix-web = "4.4.0"
env_logger = "0.10.0"
